version: '3'

services:
    cp56m:
        container_name: "cp56m"
        build: "./"
        env_file: .env
        volumes:
          - ./conf/apache.conf:/etc/httpd/conf.d/apache.conf
          - ./conf/vhosts.conf:/etc/httpd/conf.d/vhosts.conf
          - ./conf/ssmtp.conf:/etc/ssmtp/ssmtp.conf
          - ./conf/php.ini:/etc/php.ini
          - ./conf/my.cnf:/etc/my.cnf
          - ./conf/config.fish:/root/.config/fish/config.fish
          - ${WWW_DIR}:/var/www/html
          - ${SHARE_DIR}:/file
          - ./volumes/mysql:/var/lib/mysql # for mac
          # - cp56m-volume:/var/lib/mysql # for windows
        ports:
          - "8888:80"
# volumes: # for windows
#     cp56m-volume:
